<?php
if(genesis_test()):
    /**
     * Genesis Framework.
     *
     * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
     * Please do all modifications in the form of a child theme.
     *
     * @package Genesis\Templates
     * @author  StudioPress
     * @license GPL-2.0+
     * @link    http://my.studiopress.com/themes/genesis/
     */

    // Initialize Genesis.
    add_action('genesis_before_loop',array('MSDNewsCPT','do_archive_description'));
    remove_action('genesis_loop','genesis_do_loop');
    add_action('genesis_loop',array('MSDNewsCPT','custom_loop'));
    genesis();
else:
    print 'not genesis, sorry.';
endif;