<?php
if(genesis_test()):
    /**
     * Genesis Framework.
     *
     * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
     * Please do all modifications in the form of a child theme.
     *
     * @package Genesis\Templates
     * @author  StudioPress
     * @license GPL-2.0+
     * @link    http://my.studiopress.com/themes/genesis/
     */

    // Initialize Genesis.
    remove_all_actions('genesis_entry_header');
    remove_all_actions('genesis_entry_content');
    remove_all_filters('genesis_attr_content-sidebar-wrap');
    global $msd_custom;
    add_action('genesis_entry_content',array($msd_custom->artwork_class,'cpt_display'));
    genesis();
else:
    print 'not genesis, sorry.';
endif;